output = "output.png"
gap = 20
gap_background = "#222222"
infill_background = "#ffffff"
font_size = 75
text_outline_width = 5
oval_outline_width = 14

# Optional: explicit font path. If unset, searches for Helvetica, Arial, etc.
# font_path = "/usr/share/fonts/truetype/liberation/LiberationSans-Bold.ttf"

[[images]]
file = "before.png"

  [[images.texts]]
  content = "BEFORE"

[[images]]
file = "after.png"

  [[images.ovals]]
  x = 324
  y = 934
  width = 150
  height = 120

  [[images.texts]]
  content = "AFTER"

[[images]]
file = "destination.png"

  [[images.texts]]
  content = "WHERE IT\nTAKES YOU"
